"""Dataset loaders with realistic Non-IID partitioning across federated clients.

Real datasets:
  * MIT-BIH Arrhythmia (PhysioNet) — partitioned by patient record.
  * WESAD                          — partitioned by subject.
  * CICIoMT-2024                   — partitioned by protocol/device class.

For environments without the raw data on disk, ``use_synthetic_fallback=True``
generates a structured synthetic dataset that *preserves* the federation topology
(class skew, feature skew) so the framework can be exercised end-to-end. Real
runs only require dropping the dataset files into ``data/<dataset_name>/`` and
toggling the flag off.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset

from .config import DataConfig


# --------------------------------------------------------------------------- #
#                              Dataset wrappers
# --------------------------------------------------------------------------- #
class ArrayDataset(Dataset):
    def __init__(self, X: np.ndarray, y: np.ndarray) -> None:
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.int64))

    def __len__(self) -> int:
        return self.y.shape[0]

    def __getitem__(self, i: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.X[i], self.y[i]


# --------------------------------------------------------------------------- #
#                                  Real loaders
# --------------------------------------------------------------------------- #
def _load_mitbih(root: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Expect ``root/mitbih/`` containing ``X.npy`` (N, 1, 187), ``y.npy`` (N,),
    ``record_id.npy`` (N,). Pre-process with the standard 187-sample beats from
    Kachuee et al. 2018."""
    base = os.path.join(root, "mitbih")
    X = np.load(os.path.join(base, "X.npy"))
    y = np.load(os.path.join(base, "y.npy"))
    rec = np.load(os.path.join(base, "record_id.npy"))
    return X, y, rec


def _load_wesad(root: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Expect ``root/wesad/`` with ``X.npy`` (N, C, T), ``y.npy``, ``subject.npy``.
    Suggested pre-processing: 60-second windows, 700 Hz->4 Hz downsample."""
    base = os.path.join(root, "wesad")
    X = np.load(os.path.join(base, "X.npy"))
    y = np.load(os.path.join(base, "y.npy"))
    subj = np.load(os.path.join(base, "subject.npy"))
    return X, y, subj


def _load_ciciomt(root: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Expect ``root/ciciomt/`` with ``X.npy`` (N, F), ``y.npy``, ``protocol.npy``."""
    base = os.path.join(root, "ciciomt")
    X = np.load(os.path.join(base, "X.npy"))
    y = np.load(os.path.join(base, "y.npy"))
    proto = np.load(os.path.join(base, "protocol.npy"))
    return X, y, proto


def _load_ptbxl(root: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Expect ``root/ptbxl/`` with ``X.npy`` (N, 12, 1000), ``y.npy``,
    ``patient_id.npy``. Generated by ``scripts/prep_ptbxl.py`` from PhysioNet
    PTB-XL 1.0.x at 100 Hz, 5-class superdiagnostic SCP labels."""
    base = os.path.join(root, "ptbxl")
    X = np.load(os.path.join(base, "X.npy"))
    y = np.load(os.path.join(base, "y.npy"))
    pid = np.load(os.path.join(base, "patient_id.npy"))
    return X, y, pid


def _load_physionet2017(root: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """PhysioNet/CinC 2017 single-lead AF challenge. X: (N, 1, 9000) float32,
    y: 4-class (N/A/O/~). Partition: per-record_id."""
    base = os.path.join(root, "physionet2017")
    X = np.load(os.path.join(base, "X.npy"))
    y = np.load(os.path.join(base, "y.npy"))
    rid = np.load(os.path.join(base, "record_id.npy"))
    return X, y, rid


def _load_physionet2020(root: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """PhysioNet/CinC 2020 12-lead aggregate. X: (N, 12, 5000) float32,
    y: 5-class superdiagnostic, site_id: 5 source databases (PTB-XL excluded
    to avoid overlap with our PTB-XL evaluation). Partition: per-site
    (canonical multi-site healthcare-FL)."""
    base = os.path.join(root, "physionet2020")
    X = np.load(os.path.join(base, "X.npy"))
    y = np.load(os.path.join(base, "y.npy"))
    sid = np.load(os.path.join(base, "site_id.npy"))
    return X, y, sid


# --------------------------------------------------------------------------- #
#                              Synthetic fallback
# --------------------------------------------------------------------------- #
def _synthetic(name: str, num_clients: int, seed: int = 0) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Produces dataset with realistic shape and per-group distributional shift.

    Each ``group_id`` corresponds to a *natural* partition source
    (record / subject / protocol). Shifts are encoded as group-dependent class
    priors and feature offsets so Non-IID is preserved.
    """
    rng = np.random.default_rng(seed)
    if name == "mitbih":
        n_per_group, T, C = 1200, 187, 1
        n_classes = 5
    elif name == "wesad":
        n_per_group, T, C = 600, 256, 6
        n_classes = 4
    elif name == "ciciomt":
        n_per_group, T, C = 1500, 1, 32   # tabular, T=1 to fit array layout
        n_classes = 6
    elif name == "ptbxl":
        n_per_group, T, C = 200, 1000, 12     # 10s at 100 Hz, 12-lead ECG
        n_classes = 5                          # NORM, MI, STTC, CD, HYP
    elif name == "physionet2017":
        n_per_group, T, C = 800, 9000, 1      # 30s at 300 Hz, single-lead ECG
        n_classes = 4                          # N, A, O, ~ (Normal/AF/Other/Noisy)
    elif name == "physionet2020":
        n_per_group, T, C = 1500, 5000, 12    # 10s at 500 Hz, 12-lead ECG
        n_classes = 5                          # NORM, MI, STTC, CD, HYP
    else:
        raise ValueError(name)

    Xs, ys, gs = [], [], []
    for g in range(num_clients):
        cls_prior = rng.dirichlet(np.ones(n_classes) * 0.5)        # class skew
        feat_offset = rng.normal(scale=0.3, size=(C, T)) if T > 1 else rng.normal(scale=0.3, size=(C,))
        for _ in range(n_per_group):
            c = rng.choice(n_classes, p=cls_prior)
            base = rng.normal(size=(C, T)) if T > 1 else rng.normal(size=(C,))
            class_pattern = np.sin(2 * np.pi * (c + 1) * np.linspace(0, 1, T)) if T > 1 else np.array([c * 0.4])
            x = base + 0.5 * class_pattern + feat_offset
            Xs.append(x)
            ys.append(c)
            gs.append(g)
    X = np.stack(Xs).astype(np.float32)
    if X.ndim == 2:           # tabular path
        X = X.astype(np.float32)
    y = np.asarray(ys, dtype=np.int64)
    groups = np.asarray(gs, dtype=np.int64)
    return X, y, groups


# --------------------------------------------------------------------------- #
#                              Non-IID partition
# --------------------------------------------------------------------------- #
def dirichlet_partition(
    y: np.ndarray, num_clients: int, alpha: float, rng: np.random.Generator
) -> List[np.ndarray]:
    """Partition indices via a per-class Dirichlet draw (Hsu et al., 2019)."""
    n_classes = int(y.max()) + 1
    client_idx: List[List[int]] = [[] for _ in range(num_clients)]
    for c in range(n_classes):
        idx_c = np.where(y == c)[0]
        rng.shuffle(idx_c)
        proportions = rng.dirichlet(np.repeat(alpha, num_clients))
        # convert to integer split points
        proportions = (np.cumsum(proportions) * len(idx_c)).astype(int)[:-1]
        splits = np.split(idx_c, proportions)
        for k, s in enumerate(splits):
            client_idx[k].extend(s.tolist())
    return [np.asarray(ci, dtype=np.int64) for ci in client_idx]


def group_partition(group_ids: np.ndarray, num_clients: int) -> List[np.ndarray]:
    """Strict per-group partition (e.g., one subject per client). If
    ``num_clients < #groups`` we pack groups round-robin."""
    unique = np.unique(group_ids)
    buckets: List[List[int]] = [[] for _ in range(num_clients)]
    for i, g in enumerate(unique):
        buckets[i % num_clients].extend(np.where(group_ids == g)[0].tolist())
    return [np.asarray(b, dtype=np.int64) for b in buckets]


# --------------------------------------------------------------------------- #
#                              High-level API
# --------------------------------------------------------------------------- #
@dataclass
class FederatedSplit:
    client_train: List[ArrayDataset]
    client_val: List[ArrayDataset]    # used by AE thresholding
    test: ArrayDataset
    num_classes: int
    input_shape: Tuple[int, ...]


def build_federated_data(cfg: DataConfig, seed: int = 42) -> FederatedSplit:
    rng = np.random.default_rng(seed)
    name = cfg.name.lower()
    try:
        if cfg.use_synthetic_fallback or not os.path.isdir(os.path.join(cfg.root, name)):
            X, y, groups = _synthetic(name, cfg.num_clients, seed=seed)
        else:
            if name == "mitbih":
                X, y, groups = _load_mitbih(cfg.root)
            elif name == "wesad":
                X, y, groups = _load_wesad(cfg.root)
            elif name == "ciciomt":
                X, y, groups = _load_ciciomt(cfg.root)
            elif name == "ptbxl":
                X, y, groups = _load_ptbxl(cfg.root)
            elif name == "physionet2017":
                X, y, groups = _load_physionet2017(cfg.root)
            elif name == "physionet2020":
                X, y, groups = _load_physionet2020(cfg.root)
            else:
                raise ValueError(f"unknown dataset {name}")
    except FileNotFoundError:
        X, y, groups = _synthetic(name, cfg.num_clients, seed=seed)

    n = len(y)
    perm = rng.permutation(n)
    n_test = int(cfg.test_fraction * n)
    test_idx, train_idx = perm[:n_test], perm[n_test:]
    X_test, y_test = X[test_idx], y[test_idx]
    X_pool, y_pool, g_pool = X[train_idx], y[train_idx], groups[train_idx]

    # natural partition (record/subject/protocol) blended with Dirichlet skew
    natural = group_partition(g_pool, cfg.num_clients)
    if cfg.dirichlet_alpha < 50:        # add Dirichlet class skew on top
        diric = dirichlet_partition(y_pool, cfg.num_clients, cfg.dirichlet_alpha, rng)
        client_idx = []
        for a, b in zip(natural, diric):
            inter = np.intersect1d(a, b)
            client_idx.append(inter if len(inter) > 64 else a)
    else:
        client_idx = natural

    # Ensure no client is empty: redistribute from the largest
    sizes = [len(c) for c in client_idx]
    if any(s < 16 for s in sizes):
        biggest = int(np.argmax(sizes))
        for i, ci in enumerate(client_idx):
            if len(ci) < 16:
                take = max(64, 16 - len(ci))
                donor = client_idx[biggest]
                rng.shuffle(donor)
                client_idx[i] = np.concatenate([ci, donor[:take]])
                client_idx[biggest] = donor[take:]

    client_train, client_val = [], []
    cap = getattr(cfg, "max_samples_per_client", 0)
    for ci in client_idx:
        if len(ci) < 16:        # final guard: pad by sampling with replacement from pool
            extra = rng.choice(len(y_pool), size=64, replace=True)
            ci = np.concatenate([ci, extra])
        if cap and len(ci) > cap:
            ci = rng.choice(ci, size=cap, replace=False)
        rng.shuffle(ci)
        n_val = max(32, int(cfg.val_fraction * len(ci)))
        v, t = ci[:n_val], ci[n_val:]
        client_train.append(ArrayDataset(X_pool[t], y_pool[t]))
        client_val.append(ArrayDataset(X_pool[v], y_pool[v]))

    test = ArrayDataset(X_test, y_test)
    num_classes = int(y.max()) + 1
    input_shape = tuple(X.shape[1:])
    return FederatedSplit(
        client_train=client_train,
        client_val=client_val,
        test=test,
        num_classes=num_classes,
        input_shape=input_shape,
    )


def make_loader(ds: Dataset, batch_size: int, shuffle: bool = True) -> DataLoader:
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle, drop_last=False, num_workers=0)
